### ISSUE TITLE
Why do balances become incorrect?

### ISSUE THREAD

**Issue by pjr0001** [envato/double_entry#168]
Generally speaking, why do we need to run the account fixer/checker, and how often should we run it?

I just ran it today, and it found probably 20-30 calculation errors made over the past few months. I'm just curious what situations generally cause these balance miscalculations? Thanks for the awesome library btw!

**Comment by orien** [comment]
Oh dear, that shouldn't be happening. It sounds like the account locking is not working for you. What version of DoubleEntry and Rails are you using? And on which database?

**Comment by 9mm** [comment]
@orien why would balances not be working even if locking wasnt working right? Wouldn't transactions ensure that nothing is ever partially added/removed?

**Comment by 9mm** [comment]
I'm asking because I had to build my own version of double entry accounting (yours is great but didnt fit my needs)

I'm trying to think of all possible scenarios to account for. Currently I'm not using any locks, however everything is in a transaction for everything.

**Comment by zharikovpro** [comment]
@9mm without locking you can [double spend money](https://makandracards.com/makandra/31937-differences-between-transactions-and-locking), for example.

**Comment by 9mm** [comment]
I see, so it depends on getting the balance of the account so that you know how much you can spend, and that SELECT will possibly be out of date. Right?

In my case I'm only creating transactions based on external factors (pre-set amounts), so there won't really ever be SELECTS to see the balance of something

**Comment by zharikovpro** [comment]
> SELECT will possibly be out of date. Right?
Right.

> In my case I'm only creating transactions based on external factors (pre-set amounts), so there won't really ever be SELECTS to see the balance of something

Hmm, accounting system without balance reads sounds very unusual to me. Also, without reads, it's impossible to prevent overspending, i.e. spending more money that account have?

**Comment by 9mm** [comment]
There are 2 'read balance' functions in my app:

- get current account balance (e.g. balance 'Accounts Receivable')
- get current category balance (e.g. balance the `:liability` category of accounts)

Balance category is used to calculate trial balance to ensure it equals `0.0`, but all 5 SELECT statements are in the same statement so I'm 100% sure that it will always be showing the correct amount (because you can't halfway enter a transaction's line items. they all go together in a transaction). Balance category is also not used to determine HOW MUCH to create transactions for.

Balance account is used to calculate the amount someone should pay on an invoice. However, ALL transactions which are added to the invoice are done at the same time each month from a job that uses an advisory lock to make sure only 1 instance of the job is running, and it will check a flag to see if the item has already been added. So that way I know certain transactions have only been added once.

There is no spending in my app btw, it's based on invoices and payments (a SAAS service where people can log in and pay a pre-set amount in their account, which gets added each month by the job)

**Comment by zharikovpro** [comment]
> all 5 SELECT statements are in the same statement so I'm 100% sure that it will always be showing the correct amount

If you don't have parallel reads at all - i.e. one thread for one user, then yes. If not, you still need a lock, which you use. Funny enough, you use lock although in a previous comment you said you don't use locks :)

**Comment by 9mm** [comment]
Sorry, I meant I'm not using `SELECT FOR UPDATE` locks (which I haven't really used before)

Thanks for explaining

**Comment by 9mm** [comment]
Can you explain this part more

> If you don't have parallel reads at all - i.e. one thread for one user

Were you referring to the 5 selects in one statement part? That was for my trial balance which just sums all line items in an account category

**Comment by swrobel** [comment]
> Generally speaking, why do we need to run the account fixer/checker, and how often should we run it?

Still curious as to the answer to this question

**Comment by warkann** [comment]
I'm interested, too

**Comment by orien** [comment]
The account check is something of a sanity check. It's there to provide confidence that everything is working as it should be.

It shouldn't find _any_ errors!

If it does find an error, the incident should be investigated thoroughly.

In my experience, it works correctly in a highly parallel environment, under high load. If others have a different experience we should explore.

**Comment by orien** [comment]
@swrobel A scheduled job is a good idea. How often depends on the rate of transaction generation. You wouldn't want the check to be working on too many transactions at a time. As a rough guide, daily to hourly.

As for impacts, the check locks accounts as it inspects balances. So would have a small impact to the rate transactions can be generated.

**Comment by orien** [comment]
I’ll close this now as further details are not forthcoming.

If anyone has similar problems please create a new issue.
