### ISSUE TITLE
Support Rails 7

### ISSUE THREAD

**Issue by zolzaya** [envato/double_entry#214]
Hi, 

When I trying to use it with Rails 7. I get following errors.

```
rails aborted!
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Active Record release the migration was written for:

  class CreateDoubleEntryTables < ActiveRecord::Migration[7.0]
/Users/zoloo/code/lawmax-web/db/migrate/20220620000008_create_double_entry_tables.rb:1:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Active Record release the migration was written for:

  class CreateDoubleEntryTables < ActiveRecord::Migration[7.0]
/Users/zoloo/code/lawmax-web/db/migrate/20220620000008_create_double_entry_tables.rb:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace
```
It's looks like not support Rails 7.

**Comment by runlevel5** [comment]
What version of double_entry are you using? From my understanding this issue should not occur because the rails version suffix is already there in the migration template https://github.com/envato/double_entry/blob/master/lib/generators/double_entry/install/templates/migration.rb#L1. You might need to manually update `db/migrate/20220620000008_create_double_entry_tables.rb` to include `[7.0]` suffix

**Comment by zolzaya** [comment]
Thank you for quick reply. My Rails version is Rails 7.0.3.
